name: Sync Sitemap Daily

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 2 minutes
  workflow_dispatch:        # Optional manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    env:
        TOKEN:  ${{ secrets.SITEMAP_REGEN_TOKEN }}
    steps:
      - name: Call We grow wealth
        run: curl -X GET "https://a75c-49-36-179-7.ngrok-free.app/sitemap.xml/regenerate?token=$TOKEN"

      - name: Call Peddle Plus
        run: curl -X GET "https://wegrowwealth.in/sitemap.xml/regenerate?token=$TOKEN"
