name: Ping URL Daily

on:
  schedule:
    # - cron: '0 0 * * *' 
    - cron: '*/2 * * * *'
  workflow_dispatch:     # (Optional) allows manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call URL
        run: curl -X GET https://wegrowwealth.in/hello
